[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
bootloader_api = "0.11.7"
linked_list_allocator = "0.10.5"
pc-keyboard = "0.7.0"
pic8259 = "0.11.0"
spin = "0.9.8"
x86_64 = "0.15.0"
futures = { version = "0.3.30", default-features = false, features = ["alloc"] }
crossbeam = { version = "0.8.4", default-features = false, features = [
    "alloc",
] }
log = "0.4.21"

[dependencies.stdlib]
path = "../stdlib"
features = ["syscall_raw"]
