[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[profile.release]
strip = true
opt-level = 3
codegen-units = 1
panic = "abort"

[profile.dev]
opt-level = 0
panic = "abort"

[dependencies]
spin = "0.9.8"
bitflags = "2.5.0"

[dev-dependencies]
proptest = "1.4.0"
